apiVersion: apps/v1
kind: Deployment
metadata:
  name: ea-auth
  labels:
    app: ea-auth
spec:
  replicas: 2
  template:
    metadata:
      name: ea-auth
      labels:
        app: ea-auth
    spec:
      containers:
        - name: ea-auth
          image: life14ok/ea-auth
          ports:
            - containerPort: 10001
          env:
            - name: "API-KEY"
              valueFrom:
                secretKeyRef:
                  name: ea-secret
                  key: service-api-key
            - name: "PORT"
              value: "10001"
  selector:
    matchLabels:
      app: ea-auth
---
apiVersion: v1
kind: Service
metadata:
  name: ea-auth-service
spec:
  selector:
    app: ea-auth
  ports:
    - port: 10001
      targetPort: 10001
  type: ClusterIP # internal
