server:
  port: 10002
spring:
  jpa:
    database: mysql
#    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3309/account?autoReconnect=true&useSSL=false
    username: root
    password: 123456
router:
  auth:
    url: http://localhost:10001
api:
  key: ea-max-secret

