


server:
  port: ${PORT:10004}


payment:
  url: http://ea-payment-service:10005/payment
product:
  url: http://ea-product-service:10003/product

spring:
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DATABASE_HOST:localhost}:${DATABASE_PORT:3306}/account?autoReconnect=true&useSSL=false
    username: root
    password: 123456
router:
  auth:
    url: http://ea-auth-service:10001
api:
  key: ${API-KEY}