

payment:
  url: http://localhost:10005/payment
product:
  url: http://localhost:10003/product

api:
  key: ea-max-secret


spring:
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3309/account?autoReconnect=true&useSSL=false
    username: root
    password: 123456
server:
  port: 10004