apiVersion: apps/v1
kind: Deployment
metadata:
  name: ea-bank
  labels:
    app: ea-bank
spec:
  replicas: 1
  template:
    metadata:
      name: ea-bank
      labels:
        app: ea-bank
    spec:
      containers:
        - name: ea-bank
          image: life14ok/ea-bank
          ports:
            - containerPort: 10007
          env:
            - name: "API-KEY"
              valueFrom:
                secretKeyRef:
                  name: ea-secret
                  key: service-api-key
            - name: "PORT"
              value: "10007"
            - name: "DATABASE_HOST"
              value: "ea-mysql-service"
            - name: "DATABASE_PORT"
              value: "3306"
  selector:
    matchLabels:
      app: ea-bank
---
apiVersion: v1
kind: Service
metadata:
  name: ea-bank-service
spec:
  selector:
    app: ea-bank
  ports:
    - port: 10007
      targetPort: 10007
  type: ClusterIP
