
server:
  port: ${PORT:10000}
zuul:
  routes:
    example:
      path: ${spring.data.rest.base-path}/example/**
      url: http://localhost:8099/hello
    account:
      path: ${spring.data.rest.base-path}/account/**
      url: http://localhost:10002/account
spring:
  data:
    rest:
      base-path: /api
