server:
  port: ${PORT:10000}

zuul:
  routes:
    example:
      path: /api/example/**
      url: http://localhost:8099/hello
    account:
      path: /api/account/**
      url: http://localhost:10002/account/

auth-url: http://localhost:10001/auth

exclude-routes:
    urls: http://localhost:10000/api/account/login,http://localhost:10000/api/account/register
api:
  key: ea-max-secret
