server:
  port: ${PORT:10000}

zuul:
  routes:
    example:
      path: /api/example/**
      url: http://test-service:8099/hello
    account:
      path: /api/account/**
      url: http://ea-account-service:9002/account/

auth-url: http://ea-auth-service:10001
exclude-routes:
  urls: http://localhost:10000/api/account/login,http://localhost:10000/api/account/register

api:
  key: ${API-KEY}
