server:
  port: ${PORT:10000}

zuul:
  routes:
    example:
      path: /example/**
      url: http://test-service:8099/hello
    account:
      path: /account/**
      url: http://ea-account:10002/user
  ignored-patterns:
    - /account/login/**
    - /account/regiter/**
