server:
  port: ${PORT:10000}

zuul:
  routes:
    example:
      path: ${spring.data.rest.base-path}/example/**
      url: http://test-service:8099/hello
    account:
      path: ${spring.data.rest.base-path}/account/**
      url: http://ea-account-service:9002/account/
spring:
  data:
    rest:
      base-path: /api
router:
  auth:
    url: http://ea-auth-service:10001
api:
  key: ${API-KEY}
