server:
  port: ${PORT:10000}

zuul:
  routes:
    example:
      path: /api/example/**
      url: http://localhost:8099/hello
    account:
      path: /api/account/**
      url: http://localhost:10002/account/
    payment:
      path: /api/payment/**
      url: http://localhost:10010/payment/
    product:
      path: /api/product/**
      url: http://localhost:10003/product/
    order:
      path: /api/order/**
      url: http://localhost:10004/order/

auth-url: http://localhost:10001/auth

exclude-routes:
    urls: http://localhost:10000/api/account/login,http://localhost:10000/api/account/register
api:
  key: ea-max-secret
