apiVersion: apps/v1
kind: Deployment
metadata:
  name: example
  labels:
    app: example
spec:
  replicas: 1
  template:
    metadata:
      name: example
      labels:
        app: example
    spec:
      containers:
        - name: example
          image: life14ok/k8s-test
          ports:
            - containerPort: 8099
          env:
            - name: "PORT"
              value: "9999"
  selector:
    matchLabels:
      app: example
---
apiVersion: v1
kind: Service
metadata:
  name: test-service
spec:
  type: NodePort
  selector:
    app: example
  ports:
    - port: 8099 # map containerPort
      targetPort: 9999 # real spring boot port
      nodePort: 30002
---



