apiVersion: apps/v1
kind: Deployment
metadata:
  name: ea-credit
  labels:
    app: ea-credit
spec:
  replicas: 1
  template:
    metadata:
      name: ea-credit
      labels:
        app: ea-credit
    spec:
      containers:
        - name: ea-credit
          image: life14ok/ea-credit
          ports:
            - containerPort: 10008
          env:
            - name: "API-KEY"
              valueFrom:
                secretKeyRef:
                  name: ea-secret
                  key: service-api-key
            - name: "PORT"
              value: "10008"
            - name: "DATABASE_HOST"
              value: "ea-mysql-service"
            - name: "DATABASE_PORT"
              value: "3306"
  selector:
    matchLabels:
      app: ea-credit
---
apiVersion: v1
kind: Service
metadata:
  name: ea-credit-service
spec:
  selector:
    app: ea-credit
  ports:
    - port: 10008
      targetPort: 10008
  type: ClusterIP
