apiVersion: apps/v1
kind: Deployment
metadata:
  name: ea-gateway
  labels:
    app: ea-gateway
spec:
  replicas: 1
  template:
    metadata:
      name: ea-gateway
      labels:
        app: ea-gateway
    spec:
      containers:
        - name: ea-gateway
          image: life14ok/ea-gateway
          ports:
            - containerPort: 10000
          env:
            - name: "API-KEY"
              valueFrom:
                secretKeyRef:
                  name: ea-secret
                  key: service-api-key
            - name: "PORT"
              value: "10000"
  selector:
    matchLabels:
      app: ea-gateway
---
apiVersion: v1
kind: Service
metadata:
  name: ea-gateway-service
spec:
  selector:
    app: ea-gateway
  ports:
    - port: 10000
      targetPort: 10000
      nodePort: 30005
  type: NodePort
