apiVersion: apps/v1
kind: Deployment
metadata:
  name: ea-product
  labels:
    app: ea-product
spec:
  replicas: 1
  template:
    metadata:
      name: ea-product
      labels:
        app: ea-product
    spec:
      containers:
        - name: ea-product
          image: life14ok/ea-product
          ports:
            - containerPort: 10003
          env:
            - name: "API-KEY"
              valueFrom:
                secretKeyRef:
                  name: ea-secret
                  key: service-api-key
            - name: "PORT"
              value: "10003"
            - name: "DATABASE_HOST"
              value: "ea-mysql-service"
            - name: "DATABASE_PORT"
              value: "3306"
  selector:
    matchLabels:
      app: ea-product
---
apiVersion: v1
kind: Service
metadata:
  name: ea-product-service
spec:
  selector:
    app: ea-product
  ports:
    - port: 10003
      targetPort: 10003
  type: ClusterIP
