apiVersion: apps/v1
kind: Deployment
metadata:
  name: ea-paypal
  labels:
    app: ea-paypal
spec:
  replicas: 1
  template:
    metadata:
      name: ea-paypal
      labels:
        app: ea-paypal
    spec:
      containers:
        - name: ea-paypal
          image: life14ok/ea-paypal
          ports:
            - containerPort: 10006
          env:
            - name: "API-KEY"
              valueFrom:
                secretKeyRef:
                  name: ea-secret
                  key: service-api-key
            - name: "PORT"
              value: "10006"
            - name: "DATABASE_HOST"
              value: "ea-mysql-service"
            - name: "DATABASE_PORT"
              value: "3306"
  selector:
    matchLabels:
      app: ea-paypal
---
apiVersion: v1
kind: Service
metadata:
  name: ea-paypal-service
spec:
  selector:
    app: ea-paypal
  ports:
    - port: 10006
      targetPort: 10006
  type: ClusterIP
