apiVersion: apps/v1
kind: Deployment
metadata:
  name: ea-payment
  labels:
    app: ea-payment
spec:
  replicas: 2
  template:
    metadata:
      name: ea-payment
      labels:
        app: ea-payment
    spec:
      containers:
        - name: ea-payment
          image: life14ok/ea-payment
          ports:
            - containerPort: 10005
          env:
            - name: "API-KEY"
              valueFrom:
                secretKeyRef:
                  name: ea-secret
                  key: service-api-key
            - name: "PORT"
              value: "10005"
            - name: "DATABASE_HOST"
              value: "ea-mysql-service"
            - name: "DATABASE_PORT"
              value: "3306"
  selector:
    matchLabels:
      app: ea-payment
---
apiVersion: v1
kind: Service
metadata:
  name: ea-payment-service
spec:
  selector:
    app: ea-payment
  ports:
    - port: 10005
      targetPort: 10005
  type: ClusterIP
