apiVersion: apps/v1
kind: Deployment
metadata:
  name: ea-order
  labels:
    app: ea-order
spec:
  replicas: 1
  template:
    metadata:
      name: ea-order
      labels:
        app: ea-order
    spec:
      containers:
        - name: ea-order
          image: life14ok/ea-order
          ports:
            - containerPort: 10004
          env:
            - name: "API-KEY"
              valueFrom:
                secretKeyRef:
                  name: ea-secret
                  key: service-api-key
            - name: "PORT"
              value: "10004"
            - name: "DATABASE_HOST"
              value: "ea-mysql-service"
            - name: "DATABASE_PORT"
              value: "3306"
  selector:
    matchLabels:
      app: ea-order
---
apiVersion: v1
kind: Service
metadata:
  name: ea-order-service
spec:
  selector:
    app: ea-order
  ports:
    - port: 10004
      targetPort: 10004
  type: ClusterIP
